# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(320, 240)
        MainWindow.setMaximumSize(QtCore.QSize(420, 360))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.pageSwitcher = QtWidgets.QStackedWidget(self.centralWidget)
        self.pageSwitcher.setGeometry(QtCore.QRect(0, 0, 320, 240))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageSwitcher.sizePolicy().hasHeightForWidth())
        self.pageSwitcher.setSizePolicy(sizePolicy)
        self.pageSwitcher.setObjectName("pageSwitcher")
        self.homePage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homePage.sizePolicy().hasHeightForWidth())
        self.homePage.setSizePolicy(sizePolicy)
        self.homePage.setObjectName("homePage")
        self.gridLayoutWidget = QtWidgets.QWidget(self.homePage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 221))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.homeLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.homeLayout.setContentsMargins(11, 11, 11, 11)
        self.homeLayout.setSpacing(6)
        self.homeLayout.setObjectName("homeLayout")
        self.btnConfigure = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConfigure.sizePolicy().hasHeightForWidth())
        self.btnConfigure.setSizePolicy(sizePolicy)
        self.btnConfigure.setObjectName("btnConfigure")
        self.homeLayout.addWidget(self.btnConfigure, 0, 2, 1, 1)
        self.btnExit = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnExit.sizePolicy().hasHeightForWidth())
        self.btnExit.setSizePolicy(sizePolicy)
        self.btnExit.setObjectName("btnExit")
        self.homeLayout.addWidget(self.btnExit, 1, 3, 1, 1)
        self.btnPrint = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrint.sizePolicy().hasHeightForWidth())
        self.btnPrint.setSizePolicy(sizePolicy)
        self.btnPrint.setObjectName("btnPrint")
        self.homeLayout.addWidget(self.btnPrint, 1, 2, 1, 1)
        self.btnMonitor = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMonitor.sizePolicy().hasHeightForWidth())
        self.btnMonitor.setSizePolicy(sizePolicy)
        self.btnMonitor.setObjectName("btnMonitor")
        self.homeLayout.addWidget(self.btnMonitor, 0, 3, 1, 1)
        self.btnControl = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnControl.sizePolicy().hasHeightForWidth())
        self.btnControl.setSizePolicy(sizePolicy)
        self.btnControl.setMinimumSize(QtCore.QSize(0, 22))
        self.btnControl.setObjectName("btnControl")
        self.homeLayout.addWidget(self.btnControl, 0, 0, 1, 2)
        self.btnFile = QtWidgets.QToolButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFile.sizePolicy().hasHeightForWidth())
        self.btnFile.setSizePolicy(sizePolicy)
        self.btnFile.setObjectName("btnFile")
        self.homeLayout.addWidget(self.btnFile, 1, 0, 1, 2)
        self.printBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.printBar.setMaximum(100)
        self.printBar.setProperty("value", 0)
        self.printBar.setObjectName("printBar")
        self.homeLayout.addWidget(self.printBar, 2, 0, 1, 4)
        self.pageSwitcher.addWidget(self.homePage)
        self.controlPage = QtWidgets.QWidget()
        self.controlPage.setObjectName("controlPage")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.controlPage)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(9, 9, 301, 221))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnYMinus = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnYMinus.sizePolicy().hasHeightForWidth())
        self.btnYMinus.setSizePolicy(sizePolicy)
        self.btnYMinus.setObjectName("btnYMinus")
        self.gridLayout_3.addWidget(self.btnYMinus, 3, 1, 1, 1)
        self.btnYPlus = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnYPlus.sizePolicy().hasHeightForWidth())
        self.btnYPlus.setSizePolicy(sizePolicy)
        self.btnYPlus.setObjectName("btnYPlus")
        self.gridLayout_3.addWidget(self.btnYPlus, 1, 1, 1, 1)
        self.btnZPlus = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnZPlus.sizePolicy().hasHeightForWidth())
        self.btnZPlus.setSizePolicy(sizePolicy)
        self.btnZPlus.setObjectName("btnZPlus")
        self.gridLayout_3.addWidget(self.btnZPlus, 1, 3, 1, 1)
        self.btnXPlus = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnXPlus.sizePolicy().hasHeightForWidth())
        self.btnXPlus.setSizePolicy(sizePolicy)
        self.btnXPlus.setObjectName("btnXPlus")
        self.gridLayout_3.addWidget(self.btnXPlus, 2, 2, 1, 1)
        self.btnXMinus = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnXMinus.sizePolicy().hasHeightForWidth())
        self.btnXMinus.setSizePolicy(sizePolicy)
        self.btnXMinus.setObjectName("btnXMinus")
        self.gridLayout_3.addWidget(self.btnXMinus, 2, 0, 1, 1)
        self.btnHomeXY = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHomeXY.sizePolicy().hasHeightForWidth())
        self.btnHomeXY.setSizePolicy(sizePolicy)
        self.btnHomeXY.setObjectName("btnHomeXY")
        self.gridLayout_3.addWidget(self.btnHomeXY, 2, 1, 1, 1)
        self.btnHomeZ = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHomeZ.sizePolicy().hasHeightForWidth())
        self.btnHomeZ.setSizePolicy(sizePolicy)
        self.btnHomeZ.setObjectName("btnHomeZ")
        self.gridLayout_3.addWidget(self.btnHomeZ, 2, 3, 1, 1)
        self.btnZMinus = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnZMinus.sizePolicy().hasHeightForWidth())
        self.btnZMinus.setSizePolicy(sizePolicy)
        self.btnZMinus.setObjectName("btnZMinus")
        self.gridLayout_3.addWidget(self.btnZMinus, 3, 3, 1, 1)
        self.btnTen = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTen.sizePolicy().hasHeightForWidth())
        self.btnTen.setSizePolicy(sizePolicy)
        self.btnTen.setObjectName("btnTen")
        self.gridLayout_3.addWidget(self.btnTen, 4, 1, 1, 1)
        self.btnHundred = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHundred.sizePolicy().hasHeightForWidth())
        self.btnHundred.setSizePolicy(sizePolicy)
        self.btnHundred.setObjectName("btnHundred")
        self.gridLayout_3.addWidget(self.btnHundred, 4, 0, 1, 1)
        self.btnOne = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnOne.sizePolicy().hasHeightForWidth())
        self.btnOne.setSizePolicy(sizePolicy)
        self.btnOne.setObjectName("btnOne")
        self.gridLayout_3.addWidget(self.btnOne, 4, 2, 1, 1)
        self.btnHome = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHome.sizePolicy().hasHeightForWidth())
        self.btnHome.setSizePolicy(sizePolicy)
        self.btnHome.setObjectName("btnHome")
        self.gridLayout_3.addWidget(self.btnHome, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 3, 2, 1, 1)
        self.btnPointOne = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPointOne.sizePolicy().hasHeightForWidth())
        self.btnPointOne.setSizePolicy(sizePolicy)
        self.btnPointOne.setObjectName("btnPointOne")
        self.gridLayout_3.addWidget(self.btnPointOne, 4, 3, 1, 1)
        self.btnAutoLevel = QtWidgets.QToolButton(self.gridLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAutoLevel.sizePolicy().hasHeightForWidth())
        self.btnAutoLevel.setSizePolicy(sizePolicy)
        self.btnAutoLevel.setObjectName("btnAutoLevel")
        self.gridLayout_3.addWidget(self.btnAutoLevel, 1, 0, 1, 1)
        self.pageSwitcher.addWidget(self.controlPage)
        self.configurePage = QtWidgets.QWidget()
        self.configurePage.setObjectName("configurePage")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.configurePage)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 9, 301, 226))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.configureVerticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.configureVerticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.configureVerticalLayout_2.setSpacing(6)
        self.configureVerticalLayout_2.setObjectName("configureVerticalLayout_2")
        self.btnHome2 = QtWidgets.QToolButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHome2.sizePolicy().hasHeightForWidth())
        self.btnHome2.setSizePolicy(sizePolicy)
        self.btnHome2.setObjectName("btnHome2")
        self.configureVerticalLayout_2.addWidget(self.btnHome2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textServerAddr = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.textServerAddr.setObjectName("textServerAddr")
        self.horizontalLayout_2.addWidget(self.textServerAddr)
        self.btnConnect = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_2.addWidget(self.btnConnect)
        self.configureVerticalLayout_2.addLayout(self.horizontalLayout_2)
        self.textAPIKey = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.textAPIKey.setText("")
        self.textAPIKey.setObjectName("textAPIKey")
        self.configureVerticalLayout_2.addWidget(self.textAPIKey)
        self.pageSwitcher.addWidget(self.configurePage)
        self.filePage = QtWidgets.QWidget()
        self.filePage.setObjectName("filePage")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.filePage)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 301, 226))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.btnPrintSelected = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnPrintSelected.sizePolicy().hasHeightForWidth())
        self.btnPrintSelected.setSizePolicy(sizePolicy)
        self.btnPrintSelected.setObjectName("btnPrintSelected")
        self.gridLayout.addWidget(self.btnPrintSelected, 4, 1, 1, 1)
        self.listFile = QtWidgets.QListWidget(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFile.sizePolicy().hasHeightForWidth())
        self.listFile.setSizePolicy(sizePolicy)
        self.listFile.setObjectName("listFile")
        self.gridLayout.addWidget(self.listFile, 1, 0, 4, 1)
        self.btnMkDir = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMkDir.sizePolicy().hasHeightForWidth())
        self.btnMkDir.setSizePolicy(sizePolicy)
        self.btnMkDir.setObjectName("btnMkDir")
        self.gridLayout.addWidget(self.btnMkDir, 2, 1, 1, 1)
        self.btnMove = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnMove.sizePolicy().hasHeightForWidth())
        self.btnMove.setSizePolicy(sizePolicy)
        self.btnMove.setObjectName("btnMove")
        self.gridLayout.addWidget(self.btnMove, 1, 1, 1, 1)
        self.btnDelete = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelete.sizePolicy().hasHeightForWidth())
        self.btnDelete.setSizePolicy(sizePolicy)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 3, 1, 1, 1)
        self.btnHome3 = QtWidgets.QToolButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHome3.sizePolicy().hasHeightForWidth())
        self.btnHome3.setSizePolicy(sizePolicy)
        self.btnHome3.setObjectName("btnHome3")
        self.gridLayout.addWidget(self.btnHome3, 0, 0, 1, 2)
        self.pageSwitcher.addWidget(self.filePage)
        self.monitorPage = QtWidgets.QWidget()
        self.monitorPage.setObjectName("monitorPage")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.monitorPage)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(9, 9, 301, 221))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelJob = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelJob.setObjectName("labelJob")
        self.gridLayout_4.addWidget(self.labelJob, 1, 1, 1, 2)
        self.labelPrintTime = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelPrintTime.setObjectName("labelPrintTime")
        self.gridLayout_4.addWidget(self.labelPrintTime, 4, 1, 1, 2)
        self.labelStateHolder = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelStateHolder.setObjectName("labelStateHolder")
        self.gridLayout_4.addWidget(self.labelStateHolder, 5, 0, 1, 1)
        self.btnPostConnect = QtWidgets.QToolButton(self.gridLayoutWidget_5)
        self.btnPostConnect.setObjectName("btnPostConnect")
        self.gridLayout_4.addWidget(self.btnPostConnect, 5, 2, 1, 1)
        self.btnHome4 = QtWidgets.QToolButton(self.gridLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHome4.sizePolicy().hasHeightForWidth())
        self.btnHome4.setSizePolicy(sizePolicy)
        self.btnHome4.setObjectName("btnHome4")
        self.gridLayout_4.addWidget(self.btnHome4, 0, 0, 1, 3)
        self.labelSize = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelSize.setObjectName("labelSize")
        self.gridLayout_4.addWidget(self.labelSize, 2, 1, 1, 2)
        self.labelTimeLeftHolder = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelTimeLeftHolder.setObjectName("labelTimeLeftHolder")
        self.gridLayout_4.addWidget(self.labelTimeLeftHolder, 3, 0, 1, 1)
        self.labelState = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelState.setObjectName("labelState")
        self.gridLayout_4.addWidget(self.labelState, 5, 1, 1, 1)
        self.labelTimeLeft = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelTimeLeft.setObjectName("labelTimeLeft")
        self.gridLayout_4.addWidget(self.labelTimeLeft, 3, 1, 1, 2)
        self.lebelSizeHolder = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.lebelSizeHolder.setObjectName("lebelSizeHolder")
        self.gridLayout_4.addWidget(self.lebelSizeHolder, 2, 0, 1, 1)
        self.labelJobHolder = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.labelJobHolder.setObjectName("labelJobHolder")
        self.gridLayout_4.addWidget(self.labelJobHolder, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 1)
        self.pageSwitcher.addWidget(self.monitorPage)
        self.printPage = QtWidgets.QWidget()
        self.printPage.setObjectName("printPage")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.printPage)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 301, 221))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tempBed = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempBed.sizePolicy().hasHeightForWidth())
        self.tempBed.setSizePolicy(sizePolicy)
        self.tempBed.setStyleSheet("QSpinBox::up-button { subcontrol-position: top right; width: 20px; height: 30px;}\n"
"QSpinBox::down-button { subcontrol-position: bottom right; width: 20px; height: 30px;}")
        self.tempBed.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.tempBed.setMaximum(100)
        self.tempBed.setSingleStep(5)
        self.tempBed.setObjectName("tempBed")
        self.gridLayout_2.addWidget(self.tempBed, 4, 1, 2, 1)
        self.moveFeed = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.moveFeed.sizePolicy().hasHeightForWidth())
        self.moveFeed.setSizePolicy(sizePolicy)
        self.moveFeed.setStyleSheet("QSpinBox::up-button { subcontrol-position: top right; width: 20px; height: 30px;}\n"
"QSpinBox::down-button { subcontrol-position: bottom right; width: 20px; height: 30px;}")
        self.moveFeed.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.moveFeed.setMinimum(75)
        self.moveFeed.setMaximum(125)
        self.moveFeed.setProperty("value", 100)
        self.moveFeed.setObjectName("moveFeed")
        self.gridLayout_2.addWidget(self.moveFeed, 4, 2, 2, 1)
        self.numHead = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numHead.sizePolicy().hasHeightForWidth())
        self.numHead.setSizePolicy(sizePolicy)
        self.numHead.setObjectName("numHead")
        self.gridLayout_2.addWidget(self.numHead, 2, 0, 2, 1)
        self.btnHome5 = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnHome5.sizePolicy().hasHeightForWidth())
        self.btnHome5.setSizePolicy(sizePolicy)
        self.btnHome5.setObjectName("btnHome5")
        self.gridLayout_2.addWidget(self.btnHome5, 0, 0, 1, 3)
        self.numFeed = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        self.numFeed.setObjectName("numFeed")
        self.gridLayout_2.addWidget(self.numFeed, 2, 2, 2, 1)
        self.btnTPause = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTPause.sizePolicy().hasHeightForWidth())
        self.btnTPause.setSizePolicy(sizePolicy)
        self.btnTPause.setObjectName("btnTPause")
        self.gridLayout_2.addWidget(self.btnTPause, 1, 2, 1, 1)
        self.btnStart = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        self.btnStart.setObjectName("btnStart")
        self.gridLayout_2.addWidget(self.btnStart, 1, 0, 1, 1)
        self.btnStop = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout_2.addWidget(self.btnStop, 1, 1, 1, 1)
        self.tempHead = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tempHead.sizePolicy().hasHeightForWidth())
        self.tempHead.setSizePolicy(sizePolicy)
        self.tempHead.setStyleSheet("QSpinBox::up-button { subcontrol-position: top right; width: 20px; height: 30px;}\n"
"QSpinBox::down-button { subcontrol-position: bottom right; width: 20px; height: 30px;}")
        self.tempHead.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.tempHead.setMaximum(300)
        self.tempHead.setSingleStep(5)
        self.tempHead.setObjectName("tempHead")
        self.gridLayout_2.addWidget(self.tempHead, 4, 0, 2, 1)
        self.numBed = QtWidgets.QLCDNumber(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numBed.sizePolicy().hasHeightForWidth())
        self.numBed.setSizePolicy(sizePolicy)
        self.numBed.setObjectName("numBed")
        self.gridLayout_2.addWidget(self.numBed, 2, 1, 2, 1)
        self.btnSet = QtWidgets.QToolButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSet.sizePolicy().hasHeightForWidth())
        self.btnSet.setSizePolicy(sizePolicy)
        self.btnSet.setObjectName("btnSet")
        self.gridLayout_2.addWidget(self.btnSet, 6, 0, 1, 3)
        self.pageSwitcher.addWidget(self.printPage)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.pageSwitcher.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnConfigure.setText(_translate("MainWindow", "Configure"))
        self.btnExit.setText(_translate("MainWindow", "Exit"))
        self.btnPrint.setText(_translate("MainWindow", "Print..."))
        self.btnMonitor.setText(_translate("MainWindow", "Monitor"))
        self.btnControl.setText(_translate("MainWindow", "Control"))
        self.btnFile.setText(_translate("MainWindow", "File Management"))
        self.btnYMinus.setText(_translate("MainWindow", "Y-"))
        self.btnYPlus.setText(_translate("MainWindow", "Y+"))
        self.btnZPlus.setText(_translate("MainWindow", "Z+"))
        self.btnXPlus.setText(_translate("MainWindow", "X+"))
        self.btnXMinus.setText(_translate("MainWindow", "X-"))
        self.btnHomeXY.setText(_translate("MainWindow", "Home X/Y"))
        self.btnHomeZ.setText(_translate("MainWindow", "Home Z"))
        self.btnZMinus.setText(_translate("MainWindow", "Z-"))
        self.btnTen.setText(_translate("MainWindow", "10 mm"))
        self.btnHundred.setText(_translate("MainWindow", "100 mm"))
        self.btnOne.setText(_translate("MainWindow", "1 mm"))
        self.btnHome.setText(_translate("MainWindow", "Home"))
        self.btnPointOne.setText(_translate("MainWindow", "0.1mm"))
        self.btnAutoLevel.setText(_translate("MainWindow", "AutoLevel"))
        self.btnHome2.setText(_translate("MainWindow", "Home"))
        self.textServerAddr.setPlaceholderText(_translate("MainWindow", "Enter Server Address..."))
        self.btnConnect.setText(_translate("MainWindow", "Connect!"))
        self.textAPIKey.setPlaceholderText(_translate("MainWindow", "Enter OctoPrint API Key.."))
        self.btnPrintSelected.setText(_translate("MainWindow", "Print"))
        self.btnMkDir.setText(_translate("MainWindow", "Make dir"))
        self.btnMove.setText(_translate("MainWindow", "Move"))
        self.btnDelete.setText(_translate("MainWindow", "Delete"))
        self.btnHome3.setText(_translate("MainWindow", "Home"))
        self.labelJob.setText(_translate("MainWindow", "-"))
        self.labelPrintTime.setText(_translate("MainWindow", "-"))
        self.labelStateHolder.setText(_translate("MainWindow", "State"))
        self.btnPostConnect.setText(_translate("MainWindow", "Connect"))
        self.btnHome4.setText(_translate("MainWindow", "Home"))
        self.labelSize.setText(_translate("MainWindow", "-"))
        self.labelTimeLeftHolder.setText(_translate("MainWindow", "Approx. Left:"))
        self.labelState.setText(_translate("MainWindow", "-"))
        self.labelTimeLeft.setText(_translate("MainWindow", "-"))
        self.lebelSizeHolder.setText(_translate("MainWindow", "Size:"))
        self.labelJobHolder.setText(_translate("MainWindow", "Job:"))
        self.label.setText(_translate("MainWindow", "PrintTime:"))
        self.tempBed.setSuffix(_translate("MainWindow", "C"))
        self.tempBed.setPrefix(_translate("MainWindow", "T1: "))
        self.moveFeed.setSuffix(_translate("MainWindow", "%"))
        self.moveFeed.setPrefix(_translate("MainWindow", "FD: "))
        self.btnHome5.setText(_translate("MainWindow", "Home"))
        self.btnTPause.setText(_translate("MainWindow", "Pause"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.tempHead.setSuffix(_translate("MainWindow", "C"))
        self.tempHead.setPrefix(_translate("MainWindow", "T0: "))
        self.btnSet.setText(_translate("MainWindow", "Set"))

